//ERRORS 
export const GET_ERRORS = "GET_ERRORS";

//ADMIN
export const ADMIN_LOADING = "ADMIN_LOADING";
export const SET_CURRENT_ADMIN = "SET_CURRENT_ADMIN";

// EMPLOYEE
export const EMPLOYEE_LOADING = "EMPLOYEE_LOADING";
export const SET_CURRENT_EMPLOYEE = "SET_CURRENT_EMPLOYEE";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE"